/**
 * Every icon sans uses, in one place.
 *
 * Heroicons (24px outline) wherever it has a fit. Heroicons has no food or
 * diet icons, so those come from Lucide, drawn at the same stroke weight
 * (see `svg.lucide` in theme.css).
 */
export {
  ArrowLeftIcon as ArrowLeft,
  ArrowRightIcon as ArrowRight,
  ArrowTopRightOnSquareIcon as ArrowUpRight,
  ArrowUpOnSquareIcon as Share,
  ArrowsPointingInIcon as Collapse,
  ArrowsPointingOutIcon as Expand,
  ArchiveBoxIcon as Package,
  AcademicCapIcon as GraduationCap,
  BookOpenIcon as BookOpen,
  BookOpenIcon as Recipe,
  BuildingStorefrontIcon as Store,
  CakeIcon as CakeSlice,
  CalendarDaysIcon as CalendarCheck,
  ChartBarIcon as Difficulty,
  ChatBubbleLeftEllipsisIcon as MessageCircleWarning,
  CheckBadgeIcon as BadgeCheck,
  CheckIcon as Check,
  ChevronRightIcon as ChevronRight,
  ClockIcon as Clock,
  ClockIcon as Timer,
  DevicePhoneMobileIcon as Smartphone,
  DocumentMagnifyingGlassIcon as ScanSearch,
  EllipsisHorizontalIcon as Ellipsis,
  ExclamationCircleIcon as CircleAlert,
  ExclamationTriangleIcon as TriangleAlert,
  FireIcon as Flame,
  HandThumbUpIcon as ThumbsUp,
  HomeIcon as House,
  LinkIcon as Link,
  ListBulletIcon as LayoutList,
  MagnifyingGlassIcon as Search,
  MagnifyingGlassIcon as SearchX,
  MapIcon as Map,
  MapIcon as Navigation,
  MapPinIcon as MapPin,
  ShieldCheckIcon as ShieldCheck,
  ShieldExclamationIcon as ShieldQuestionMark,
  ShoppingBagIcon as ShoppingBasket,
  SparklesIcon as Sparkles,
  StarIcon as Star,
  SunIcon as Sunrise,
  TrophyIcon as Trophy,
  UserCircleIcon as CircleUserRound,
  UsersIcon as Users,
  ViewfinderCircleIcon as LocateFixed,
  XMarkIcon as LocateOff,
  XMarkIcon as Close,
} from '@heroicons/react/24/outline'

export {
  ChefHat,
  Coffee,
  CookingPot,
  Cookie,
  Croissant,
  Droplets,
  EggOff,
  MilkOff,
  NutOff,
  Sandwich,
  Utensils,
  Vegan,
  WheatOff,
} from 'lucide-react'
